In [1]:
import numpy as np
import pandas as pd

In [2]:
data_1 = pd.read_csv("TB_Data_2.csv")

In [3]:
data_1.isnull().sum(axis=0)

BookingStatus    0
Wno              0
ClassOfTravel    0
JourneyDate      0
Weekdays         0
Month            0
Days             0
Astatus          0
dtype: int64

In [4]:
data_1.head()

BookingStatus  Wno ClassOfTravel JourneyDate  Weekdays  Month  Days  Astatus
0            WL    9            3A   2/12/2016         6     12     2        1
1            WL    3            3A   1/12/2016         5     12     1        1
2            WL    1            2A   3/12/2016         7     12     3        0
3            WL   67            SL   3/12/2016         7     12     3        0
4            WL   61            SL   3/12/2016         7     12     3        0

In [5]:
data_1.drop(['JourneyDate'], 1, inplace=True)

In [6]:
data_1.head()

BookingStatus  Wno ClassOfTravel  Weekdays  Month  Days  Astatus
0            WL    9            3A         6     12     2        1
1            WL    3            3A         5     12     1        1
2            WL    1            2A         7     12     3        0
3            WL   67            SL         7     12     3        0
4            WL   61            SL         7     12     3        0

In [9]:
X = data_1.values[:,0:6]
y = data_1.values[:,6]
y=y.astype('int')
y

array([1, 1, 0, ..., 0, 0, 0])

In [10]:
X[:,0]=pd.factorize(X[:,0])[0]
X[:,2]=pd.factorize(X[:,2])[0]
X

array([[0, 9, 0, 6, 12, 2],
       [0, 3, 0, 5, 12, 1],
       [0, 1, 1, 7, 12, 3],
       ...,
       [1, 58, 2, 6, 7, 20],
       [1, 52, 2, 6, 7, 20],
       [1, 19, 2, 6, 7, 20]], dtype=object)

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state=0)

In [12]:
from sklearn.linear_model import LogisticRegression
cf =LogisticRegression()

In [13]:
cf.fit(X_train, y_train)

C:\Users\Lenovo\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [18]:
Y_pred = cf.predict(X_test)

In [22]:
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, Y_pred)
cnf_matrix

array([[626,   0],
       [181,   0]], dtype=int64)

In [27]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
Log_roc = roc_auc_score(y_test, cf.predict(X_test))
fpr, tpr, thresholds=roc_curve(y_test, cf.predict_proba(X_test)[:,1])

In [32]:
plt.figure()
plt.plot(fpr,tpr, label='Train Ticket prediction (area='%0.2f')% Log_ROC_auc)
plt.xlabel('False positive rate')
plt.ylabel('True positive rate')
plt.sshow

SyntaxError: EOL while scanning string literal (<ipython-input-32-3a70ce935f89>, line 2)